# Generated by Django 2.2.24 on 2023-03-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('token_quantity', models.IntegerField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.Election')),
            ],
        ),
    ]
