# Generated by Django 2.2.24 on 2023-03-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0007_auto_20230320_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votersnapshot',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='votersnapshot',
            name='pkh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='votersnapshot',
            name='skh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
